name: Generate Snake
    
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: hyqskevin
          outputs: |
            dist/github-snake.svg
      - run: cp dist/github-snake.svg snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          add: snake.svg
          message: "docs: update snake game"
